name: Deploy to Nginx Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Stop & remove old container (if exists)
      - name: Stop old container
        run: |
          docker stop my-nginx || true
          docker rm my-nginx || true

      # Run new nginx container
      - name: Run Nginx container
        run: |
          docker run -d -p 82:80 --name my-nginx nginx

      # Copy code into container
      - name: Copy files to Nginx
        run: |
          docker cp . my-nginx:/usr/share/nginx/html/

      # Restart container to reflect changes
      - name: Restart container
        run: |
          docker restart my-nginx
